export type { ScopeId } from './scope-id'
export { ScopeManager, type ScopeManagerOptions } from './registry'
export { LruScopeManager, type LruScopeManagerOptions } from './lru-registry'
export { createOccupancyGate, type OccupancyGate } from './occupancy-gate'
export { createRefreshGuard, type RefreshGuard } from './refresh-guard'
export { buildScopedKey } from './scoped-key'
export { createWebLocksLock, createNoopLock, type SharedLock, type LockRunInfo, type WebLocksLike } from './web-locks-lock'
